- name: Install and configure FRRouting on routers
  hosts: all
  become: true
  tasks:
    - name: Install FRR package
      apt:
        name: frr
        state: present
        update_cache: yes

    - name: Enable OSPFd in FRR configuration
      lineinfile:
        path: /etc/frr/daemons
        regexp: '^ospfd='
        line: 'ospfd=yes'

    - name: Create dummy interface simulating OVS connection
      shell: |
        ip link add {{ inventory_hostname }}-veth type dummy || true
        ip link set {{ inventory_hostname }}-veth up
        ip addr add {{ '10.0.0.11' if inventory_hostname == 'router1' else '10.0.0.12' }}/24 dev {{ inventory_hostname }}-veth

    - name: Generate FRR configuration file
      copy:
        dest: /etc/frr/frr.conf
        content: |
          frr defaults traditional
          hostname {{ inventory_hostname }}
          log stdout
          !
          interface {{ inventory_hostname }}-veth
           ip address {{ '10.0.0.11/24' if inventory_hostname == 'router1' else '10.0.0.12/24' }}
          !
          router ospf
           network 10.0.0.0/24 area 0
          !
    - name: Restart FRR service
      systemd:
        name: frr
        enabled: true
        state: restarted
