- name: Install and configure FRRouting on routers
  hosts: all
  become: true
  tasks:
    - name: Install FRR package
      ansible.builtin.apt:
        name: frr
        state: present
        update_cache: true

    - name: Enable OSPFd in FRR configuration
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: '^ospfd='
        line: 'ospfd=yes'

    - name: Create dummy interface simulating OVS connection
      ansible.builtin.shell:
        cmd: |
          ip link add {{ inventory_hostname }}-veth type dummy || true
          ip link set {{ inventory_hostname }}-veth up
          ip addr add {{ '10.0.0.11' if inventory_hostname == 'router1' else '10.0.0.12' }}/24 dev {{ inventory_hostname }}-veth
        creates: "{{ inventory_hostname }}-veth"

    - name: Generate FRR configuration file
      ansible.builtin.copy:
        dest: /etc/frr/frr.conf
        content: |
          frr defaults traditional
          hostname {{ inventory_hostname }}
          log stdout
          !
          interface {{ inventory_hostname }}-veth
           ip address {{ '10.0.0.11/24' if inventory_hostname == 'router1' else '10.0.0.12/24' }}
          !
          router ospf
           network 10.0.0.0/24 area 0
          !
        mode: '0644'
        owner: frr
        group: frr

    - name: Enable FRR service
      ansible.builtin.systemd:
        name: frr
        enabled: true
        state: started

    - name: Restart FRR service
      ansible.builtin.systemd:
        name: frr
        enabled: true
        state: restarted
