- name: Setup controller with OVS and Ryu
  hosts: controller
  become: true
  tasks:
    - name: Install OVS and dependencies
      ansible.builtin.apt:
        name:
          - openvswitch-switch
          - wget
          - git
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - curl
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libffi-dev
          - liblzma-dev
          - python3-openssl
        state: present
        update_cache: true

    - name: Install pyenv for vagrant user
      ansible.builtin.shell: curl https://pyenv.run | bash

    - name: Install Python 3.9.13 with pyenv
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        pyenv install 3.9.13
    
    - name: Install pyenv-virtualenv plugin
      ansible.builtin.shell: |
        git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"

    - name: Create Ryu directory
      ansible.builtin.file:
        path: /opt/ryu
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Create virtualenv with pyenv
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"
        pyenv virtualenv 3.9.13 ryu-venv

    - name: Copy Ryu requirements to directory
      ansible.builtin.copy:
        src: files/requirements.txt
        dest: /opt/ryu/requirements.txt
        mode: '0644'
        owner: vagrant
        group: vagrant

    - name: Install requirements and activate pyenv virtualenv
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        eval "$(pyenv init --path)"
        eval "$(pyenv virtualenv-init -)"
        pyenv shell ryu-venv
        pip install -r /opt/ryu/requirements.txt
      become_user: vagrant
      args:
        executable: /bin/bash
        
    - name: Create bridge OVS and add ports
      ansible.builtin.shell: |
        ovs-vsctl add-br br0 || true
        ip link add veth1 type veth peer name r1-veth
        ip link add veth2 type veth peer name r2-veth
        ip link set veth1 up
        ip link set veth2 up
        ovs-vsctl add-port br0 veth1 || true
        ovs-vsctl add-port br0 veth2 || true
        ovs-vsctl set-controller br0 tcp:192.168.56.10:6633
        ip link set r1-veth up
        ip link set r2-veth up
        ip addr add 10.0.0.1/24 dev r1-veth
        ip addr add 10.0.0.2/24 dev r2-veth
      args:
        creates: /opt/ryu/switch.py
        executable: /bin/bash

    - name: Copy Ryu script to the controller
      ansible.builtin.copy:
        src: files/switch.py
        dest: /opt/ryu/switch.py
        mode: '0755'
        owner: vagrant
        group: vagrant

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: files/ryu.service
        dest: /etc/systemd/system/ryu.service
        mode: '0644'
        owner: root
        group: root

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Activate and start the service
      ansible.builtin.systemd:
        name: ryu
        enabled: true
        state: started
