- name: Install and configure FRRouting on routers
  hosts: all
  become: true
  tasks:
    - name: Install FRR package
      ansible.builtin.apt:
        name: frr
        state: present
        update_cache: true

    - name: Enable zebra in FRR daemons config
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: '^zebra='
        line: 'zebra=yes'

    - name: Enable OSPFd in FRR daemons config
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: '^ospfd='
        line: 'ospfd=yes'

    - name: Generate FRR configuration file
      ansible.builtin.copy:
        dest: /etc/frr/frr.conf
        content: |
          frr defaults traditional
          hostname {{ inventory_hostname }}
          log stdout
          !
          interface eth2
          ip address {{ '10.0.0.11/24' if inventory_hostname == 'router1' else '10.0.0.12/24' }}
          !
          router ospf
          network 10.0.0.0/24 area 0
          !
        mode: '0644'
        owner: frr
        group: frr

    - name: Enable and restart FRR service
      ansible.builtin.systemd:
        name: frr
        enabled: true
        state: restarted