---
- name: Install Grafana and Prometheus  (Debian)
  hosts: monitoring
  become: true
  vars:
    prometheus_version: "2.51.1"
    node_exporter_version: "1.8.1"

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - software-properties-common
          - apt-transport-https
          - wget
          - curl
        state: present
        update_cache: yes

    # GRAFANA
    - name: Add Grafana GPG key
      ansible.builtin.apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
        filename: grafana

    - name: Install Grafana
      ansible.builtin.apt:
        name: grafana
        state: present

    - name: Activate and start Grafana
      ansible.builtin.systemd:
        name: grafana-server
        enabled: true
        state: started

    # PROMETHEUS
    - name: Create Prometheus folders
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Download Prometheus {{ prometheus_version }}
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Copy Prometheus binaries
      copy:
        remote_src: yes
        src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
      loop:
        - prometheus
        - promtool

    - name: Copy custom prometheus.yml configuration
      copy:
        src: files/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        mode: "0644"

    - name: Copy Prometheus configuration files
      copy:
        remote_src: yes
        src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
      loop:
        - consoles
        - console_libraries

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target
        mode: "0644"

    - name: Start and activate Prometheus
      systemd:
        name: prometheus
        enabled: true
        state: started
