---
- name: Install and configure FRRouting on routers
  hosts: frr_routers
  become: true

  vars:
    frr_config_path: /etc/frr/frr.conf

  tasks:
    - name: Install FRR package
      ansible.builtin.apt:
        name: frr
        state: present
        update_cache: true

    - name: Enable zebra daemon
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: "^zebra="
        line: "zebra=yes"

    - name: Enable ospfd daemon
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: "^ospfd="
        line: "ospfd=yes"

    - name: Create FRR configuration
      ansible.builtin.template:
        src: templates/frr.conf.j2
        dest: "{{ frr_config_path }}"
        owner: frr
        group: frr
        mode: "0644"

    - name: Enable and restart FRR
      ansible.builtin.systemd:
        name: frr
        enabled: true
        state: restarted
