---
- name: Install and configure FRRouting on routers
  hosts: all
  become: true
  tasks:
    - name: Install FRR package
      ansible.builtin.apt:
        name: frr
        state: present
        update_cache: true

    - name: Enable zebra in FRR daemons config
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: "^zebra="
        line: "zebra=yes"

    - name: Enable OSPFd in FRR daemons config
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: "^ospfd="
        line: "ospfd=yes"

    - name: Generate FRR configuration file
      ansible.builtin.copy:
        dest: /etc/frr/frr.conf
        content: |
          frr defaults traditional
          hostname {{ inventory_hostname }}
          log stdout
          !
          {% if inventory_hostname == 'router1' %}
          interface eth1
          ip address 192.168.56.11/24
          exit
          interface eth2
          ip address 192.168.10.254/24
          exit
          router ospf
          network 192.168.56.0/24 area 0
          network 192.168.10.0/24 area 0
          exit
          {% elif inventory_hostname == 'router2' %}
          interface eth1
          ip address 192.168.56.12/24
          exit
          interface eth2
          ip address 192.168.20.254/24
          exit
          router ospf
          network 192.168.56.0/24 area 0
          network 192.168.20.0/24 area 0
          exit
          {% endif %}
        mode: "0644"
        owner: frr
        group: frr

    - name: Enable and restart FRR service
      ansible.builtin.systemd:
        name: frr
        enabled: true
        state: restarted
